#!/bin/bash
# Prints the Homebrew cask for a Jots release. The release workflow writes it to Casks/jots.rb in
# yehogwon/homebrew-vibes, which is what `brew install --cask yehogwon/vibes/jots` reads, so edit
# the cask here rather than there.
#
#   ./cask.sh VERSION SHA256
set -euo pipefail

if [ $# -ne 2 ]; then
  echo "usage: $0 VERSION SHA256" >&2
  exit 1
fi
VERSION="$1"
SHA256="$2"

cat <<EOF
# Generated by jots/cask.sh in yehogwon/vibes. Edit it there.
cask "jots" do
  version "$VERSION"
  sha256 "$SHA256"

  url "https://github.com/yehogwon/vibes/releases/download/jots-v#{version}/Jots-#{version}.zip"
  name "Jots"
  desc "Markdown scratchpad for the menu bar"
  homepage "https://github.com/yehogwon/vibes"

  # Matches LSMinimumSystemVersion in jots/Resources/Info.plist.
  depends_on macos: :sonoma

  app "Jots.app"

  uninstall quit: "io.github.yehogwon.Jots"

  # The iCloud Drive › Jots folder is left alone: deleting it would delete the text on every Mac.
  zap trash: [
    "~/Library/Application Support/Jots",
    "~/Library/Containers/io.github.yehogwon.Jots",
    "~/Library/Preferences/io.github.yehogwon.Jots.plist",
  ]

  caveats <<~EOS
    Jots is signed ad hoc, not notarized, so macOS blocks it the first time it opens. Allow it
    under System Settings › Privacy & Security › Open Anyway.
  EOS
end
EOF
