#!/bin/bash
# Prints the Homebrew cask for a Moments release. The release workflow writes it to
# Casks/moments.rb in yehogwon/homebrew-vibes, which is what
# `brew install --cask yehogwon/vibes/moments` reads, so edit the cask here rather than there.
#
#   ./cask.sh VERSION SHA256
set -euo pipefail

if [ $# -ne 2 ]; then
  echo "usage: $0 VERSION SHA256" >&2
  exit 1
fi
VERSION="$1"
SHA256="$2"

cat <<EOF
# Generated by moments/cask.sh in yehogwon/vibes. Edit it there.
cask "moments" do
  version "$VERSION"
  sha256 "$SHA256"

  url "https://github.com/yehogwon/vibes/releases/download/moments-v#{version}/Moments-#{version}.zip"
  name "Moments"
  desc "D-day countdowns for the menu bar"
  homepage "https://github.com/yehogwon/vibes"

  # Matches LSMinimumSystemVersion in moments/Resources/Info.plist.
  depends_on macos: :tahoe

  app "Moments.app"

  # Moments is signed ad hoc and can't be notarized, so Gatekeeper would block it after every
  # install and upgrade. This can't be postflight_steps, as brew style's Cask/InstallSteps wants:
  # those run sandboxed, and macOS won't let a sandboxed process clear the quarantine flag.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Moments.app"]
  end

  uninstall quit: "io.github.yehogwon.Moments"

  # The iCloud Drive › Moment folder is left alone: the original Moment syncs through it too, and
  # deleting it would delete the moments on every Mac.
  zap trash: [
    "~/Library/Application Support/Moments",
    "~/Library/Preferences/io.github.yehogwon.Moments.plist",
  ]

  caveats <<~EOS
    Moments is signed ad hoc, not notarized, so this cask clears its quarantine flag and macOS
    opens it without a Gatekeeper check.
  EOS
end
EOF
