#!/bin/bash
# Prints the Homebrew cask for a Counts release. The release workflow writes it to
# Casks/counts.rb in yehogwon/homebrew-vibes, which is what
# `brew install --cask yehogwon/vibes/counts` reads, so edit the cask here rather than there.
#
#   ./cask.sh VERSION SHA256
set -euo pipefail

if [ $# -ne 2 ]; then
  echo "usage: $0 VERSION SHA256" >&2
  exit 1
fi
VERSION="$1"
SHA256="$2"

cat <<EOF
# Generated by counts/cask.sh in yehogwon/vibes. Edit it there.
cask "counts" do
  version "$VERSION"
  sha256 "$SHA256"

  url "https://github.com/yehogwon/vibes/releases/download/counts-v#{version}/Counts-#{version}.zip"
  name "Counts"
  desc "Timers for the menu bar"
  homepage "https://github.com/yehogwon/vibes"

  # Matches LSMinimumSystemVersion in counts/Resources/Info.plist.
  depends_on macos: :sonoma

  app "Counts.app"

  # Counts is signed ad hoc and can't be notarized, so Gatekeeper would block it after every
  # install and upgrade. This can't be postflight_steps, as brew style's Cask/InstallSteps wants:
  # those run sandboxed, and macOS won't let a sandboxed process clear the quarantine flag.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Counts.app"]
  end

  uninstall quit: "io.github.yehogwon.Counts"

  # The iCloud Drive › Counts folder is left alone: deleting it would delete the timers on every
  # Mac.
  zap trash: [
    "~/Library/Application Support/Counts",
    "~/Library/Preferences/io.github.yehogwon.Counts.plist",
  ]

  caveats <<~EOS
    Counts is signed ad hoc, not notarized, so this cask clears its quarantine flag and macOS
    opens it without a Gatekeeper check.
  EOS
end
EOF
